apiVersion: v1
kind: Service
metadata:
  name: session-db
  namespace: sock-shop
  labels:
    name: session-db
spec:
  ports:
    # the port that this service should serve on
    - port: 6379
      targetPort: 6379
  selector:
    name: session-db
