apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: sock-shop
  annotations:
    prometheus.io/scrape: "true"
  labels:
    name: catalogue
spec:
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: 80
  selector:
    name: catalogue
